- src/mixins/baseTableMixin/baseTableMixin.js
- src/mixins/baseTableMixin/tableActionsMixin.js
- src/mixins/editComponentMixin.js
- src/mixins/openedObjectMixin/nestedObjectMixin.js
- src/mixins/openedObjectMixin/openedObjectMixin.js
- src/mixins/openedObjectTableTabMixin/openedObjectTableTabMixin.js
- src/mixins/openedObjectValidationMixin/openedObjectValidationMixin.js
- src/mixins/openedTabComponentMixin.js
- src/mixins/tableComponentMixin.js
added specific mixins for nested- and openedObjects, openedObjectTableTab and Validation
refactored old mixins, built hierarchy mixin
> refactor: added new object-related mixins, refactored old ones [WTEL-1672]

- src/components/contact-center/members/the-queue-members.vue
- src/components/directory/users/opened-user.vue
- src/mixins/editComponentMixin.js
- src/mixins/openedObjectMixin/nestedObjectMixin.js
https://my.webitel.com/browse/WTEL-1695
> fix: fixed admin: opened-entites reset issue [WTEL-1695]

- src/components/shared/app-header/app-header.vue
- src/store/modules/userinfo/_internals/enums/Objects.enum.js
- src/store/modules/userinfo/_internals/scripts/convertScope.js
- src/store/modules/userinfo/userinfo.js
added scope mapping script and computing which pages to show in nav depending on user access scope
> feature: added nav visibility restrictions [WTEL-1211]

- src/modules/lookups/modules/calendars/components/opened-calendar-general.vue
> fix: calendar listener fixed [wtel-1953]

- src/modules/integrations/modules/storage/components/opened-storage-general.vue
- src/modules/integrations/modules/storage/components/opened-storage.vue
> fix: storage inputs save negative numbers (bug 68) [WTEL-1953]

- src/modules/contact-center/modules/agents/api/agents.js
- src/modules/contact-center/modules/agents/components/opened-agent-general.vue
- src/modules/contact-center/modules/queues/components/preview-dialer/opened-queue-preview-dialer-general.vue
- src/modules/contact-center/modules/teams/components/opened-team-general.vue
- src/modules/contact-center/modules/teams/modules/supervisors/components/opened-team-supervisors-popup.vue
Excuse me, no possibility to push into previous pull request, so I'm creating another one.
> fix: updated filters supervisor (bug 48) [WTEL-1953]

- src/modules/contact-center/modules/queues/modules/members/components/upload-members-popup.vue
> fix: adding priority default value [WTEL-2640]

- src/modules/contact-center/modules/agents/api/agents.js
- src/modules/contact-center/modules/agents/components/opened-agent-general.vue
- src/modules/contact-center/modules/agents/components/opened-agent.vue
- src/modules/contact-center/modules/agents/store/agents.js
Add media select in agent card
> feature:add media select in card agent[WTEL-2659]

- src/app/locale/ru/ru.js
fix: name of the storage section
> fix: name of the storage section[WTEL-2825]

- package-lock.json
- package.json
- src/app/locale/ua/ua.js
> fix: errors in fields[WTEL-2832]

- src/modules/_shared/permissions-tab/components/_internals/permissions-role-select.vue
names of user roles in the select
> fix: display of role names[WTEL-2826]

- src/modules/_shared/permissions-tab/components/_internals/permissions-role-select.vue
Added correct display of roles in popup
> fix: added correct display of roles in popup[WTEL-2826]

- src/app/locale/en/en.js
- src/app/locale/ru/ru.js
- src/app/locale/ua/ua.js
- src/modules/contact-center/modules/queues/modules/logs/components/opened-queue-logs.vue
- src/modules/contact-center/modules/queues/modules/logs/store/_internals/headers.js
Added display of a column with the number of attempts in the queue logs
> feature: added display of a column with the number of attempts in the queue logs [WTEL-2862]

- src/modules/contact-center/modules/queues/modules/members/api/queueMembers.js
- src/modules/contact-center/modules/queues/modules/members/components/upload-members-popup.vue
- src/modules/contact-center/modules/queues/modules/members/mixins/normalizeCsvMembers.js
adding operator field in download from the csv file in members
> feature: adding operator field in download from the csv file in members[WTEL-2950]

- src/modules/contact-center/modules/queues/modules/members/store/queue-members.js
field 'expireAt' is increesed to 7 days
> field 'expireAt' is increesed to 7 days

- package-lock.json
- package.json
- src/modules/routing/modules/flow/modules/code/lookups/FlowAppAutocomplete.lookup.js
Autocomplete check for get email node
> feature: autocomplete check for getEemail node[WTEL-2747]

- src/modules/_shared/permissions-tab/components/_internals/permissions-role-column.vue
Permissions -> Objects -> [users] -> Managed by operations [WTEL-4536]
[WTEL-4536]: https://webitel.atlassian.net/browse/WTEL-4536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: Icon size is reduced if the user has a long role value.

- src/modules/settings/components/the-settings.vue
> Revert "Fix/settings delete language"

- src/app/mixins/baseMixins/openedObjectValidationMixin/openedObjectValidationMixin.js
https://webitel.atlassian.net/browse/WTEL-5177
> fix save button validation behavior [WTEL-5177]

- src/modules/application-hub/components/application-hub.vue
(https://webitel.atlassian.net/browse/WTEL-6764)
> fix: change name of webitelApplication for grafana [WTEL-6764]

- src/modules/settings/components/notifications-sounds.vue
(https://webitel.atlassian.net/browse/WTEL-6860)
> hotfix: add import in notifications-sounds.vue styles [WTEL-6860]

- src/modules/settings/components/notifications-sounds.vue
(https://webitel.atlassian.net/browse/WTEL-6860)
> fix: add import in notifications-sounds.vue styles [WTEL-6860]

- src/modules/settings/components/notifications-sounds.vue
(https://webitel.atlassian.net/browse/WTEL-6860)
> fix: change title locale notifications-sounds.vue [WTEL-6860]

- src/modules/lookups/modules/working-conditions/api/workingConditions.js
- src/modules/lookups/modules/working-conditions/store/working-conditions.js
to do: remove fields from array if they are not required and have default values
task: https://webitel.atlassian.net/browse/WTEL-6554
> fix: remove fields from array if they are not required and have default values [WTEL-6554] 

- src/modules/lookups/modules/communications/components/the-communication-types.vue
to do: load data without loader when change radiobutton for removed bounce page
task: https://webitel.atlassian.net/browse/WTEL-7582
> fix: load data without loader when change radiobutton for removed bounce page[WTEL-7582] 
